### ISSUE TITLE
About commerciumd -conf=xxx.conf command line processing

### ISSUE THREAD

**Issue by LatinoMiner** [CommerciumBlockchain/Commercium#1]
The arg -conf is not processed by the command line processor. I'll look inside the code to check better.
I think it is very little bug because if you make a conf under your home dir it works.
Anyway I strongly suggest a warning message if some args is captured but not processed.

**Comment by anthony19114** [comment]
hellomoto@stage:~/stage/Commercium/src$ ./commerciumd -conf=/tmp/commercium.conf
Commercium server starting
works
hellomoto@stage:~/stage/Commercium/src$ ls -aul /home/hellomoto/.commercium/commercium.conf
ls: cannot access '/home/hellomoto/.commercium/commercium.conf': No such file or directory
hellomoto@stage:~/stage/Commercium/src$
no commercium.conf there
so -conf works on external home directory
also
hellomoto@stage:~/stage/Commercium/src$ killall -9 commerciumd
hellomoto@stage:~/stage/Commercium/src$ ./commerciumd -conf=/home/hellomoto/commercium.conf
Commercium server starting
works on commercium.conf in home directory
the cookie thing is only when you dont have a rpcuser or password set because you dont have a commercium.conf in your .commercium folder in your home directory
I dont see any issue
